interface Feature {
  name: string;
  description?: string;
  pro: boolean | string;
  enterprise: boolean | string;
}

export const features: Feature[] = [
  {
    name: 'pricing_plan.data_source_integration',
    pro: 'pricing_plan.integration_limit',
    enterprise: 'pricing_plan.unlimited_integration',
  },
  {
    name: 'pricing_plan.premium_engagement_channels',
    description: 'pricing_plan.engagement_channels',
    pro: true,
    enterprise: true,
  },
  {
    name: 'pricing_plan.automated_segmentation',
    pro: true,
    enterprise: true,
  },
  {
    name: 'pricing_plan.sales_bot',
    description: 'pricing_plan.messenger',
    pro: true,
    enterprise: true,
  },
  {
    name: 'pricing_plan.campaign_performance_insights',
    pro: true,
    enterprise: true,
  },
  {
    name: 'pricing_plan.monitoring',
    pro: true,
    enterprise: true,
  },
  {
    name: 'pricing_plan.lead_booking_system',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.advanced_personalization',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.ai_constitutions',
    description: 'pricing_plan.customizable_ai_rules',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.predictive_segmentation',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.real_time_recommendations',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.personalized_assistance',
    description: 'pricing_plan.account_manager_support',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.detailed_reports',
    description: 'pricing_plan.real_time_tracking',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.enterprise_security',
    description: 'pricing_plan.enhanced_security',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.priority_support',
    description: 'pricing_plan.support_24_7',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.onboarding_training',
    description: 'pricing_plan.comprehensive_training',
    pro: false,
    enterprise: true,
  },
  {
    name: 'pricing_plan.whatsapp_addon_cost',
    pro: true,
    enterprise: false,
  },
];

export interface PricingPlan {
  id: string;
  name: string;
  description: string;
  price: string | 'Custom';
  userLimit: string;
  features: {
    whatsapp: {
      unlimited: boolean;
    };
  };
  range: string;
}

export const monthlyActiveUser = [
  { value: 10000, label: '<10K', monthly: '62.33', yearly: '673.20', plan: 'pro_1' },
  { value: 50000, label: '<50K', monthly: '311.67', yearly: '3366.04', plan: 'pro_2' },
  { value: 100000, label: '<100K', monthly: '623.33', yearly: '6731.96', plan: 'pro_3' },
  { value: 500000, label: '<500K', monthly: '3116.67', yearly: '33660.04', plan: 'pro_4' },
];

export const whatsAppUnitList = [
  { label: '1000', value: '1' },
  { label: '2000', value: '2' },
  { label: '3000', value: '3' },
  { label: '4000', value: '4' },
  { label: '5000', value: '5' },
  { label: '6000', value: '6' },
  { label: '7000', value: '7' },
  { label: '8000', value: '8' },
  { label: '9000', value: '9' },
  { label: '10000', value: '10' },
];

export const countryData = [
  { label: 'Argentina', value: 'AR', price: 61.8 },
  { label: 'Brazil', value: 'BR', price: 62.5 },
  { label: 'Chile', value: 'CL', price: 88.9 },
  { label: 'Colombia', value: 'CO', price: 12.5 },
  { label: 'Egypt', value: 'EG', price: 107.3 },
  { label: 'France', value: 'FR', price: 143.2 },
  { label: 'Germany', value: 'DE', price: 136.5 },
  { label: 'India', value: 'IN', price: 10.7 },
  { label: 'Indonesia', value: 'ID', price: 41.1 },
  { label: 'Israel', value: 'IL', price: 35.3 },
  { label: 'Italy', value: 'IT', price: 69.1 },
  { label: 'Malaysia', value: 'MY', price: 86.0 },
  { label: 'Mexico', value: 'MX', price: 43.6 },
  { label: 'Netherlands', value: 'NL', price: 159.7 },
  { label: 'Nigeria', value: 'NG', price: 51.6 },
  { label: 'Pakistan', value: 'PK', price: 47.3 },
  { label: 'Peru', value: 'PE', price: 70.3 },
  { label: 'Russia', value: 'RU', price: 80.2 },
  { label: 'Saudi Arabia', value: 'SA', price: 45.5 },
  { label: 'South Africa', value: 'ZA', price: 37.9 },
  { label: 'Spain', value: 'ES', price: 61.5 },
  { label: 'Turkey', value: 'TR', price: 10.9 },
  { label: 'United Arab Emirates', value: 'AE', price: 38.4 },
  { label: 'United Kingdom', value: 'GB', price: 52.9 },
  { label: 'North America', value: 'NA', price: 25.0 },
  { label: 'Rest of Africa', value: 'AF', price: 22.5 },
  { label: 'Rest of Asia Pacific', value: 'AP', price: 73.2 },
  { label: 'Rest of Central & Eastern Europe', value: 'CEE', price: 86.0 },
  { label: 'Rest of Latin America', value: 'LATAM', price: 74.0 },
  { label: 'Rest of Middle East', value: 'ME', price: 34.1 },
  { label: 'Rest of Western Europe', value: 'WE', price: 59.2 },
  { label: 'Other', value: 'OTHER', price: 60.4 },
];

export const COUNTRY_CODES = [
  { label: 'Afghanistan', value: 'AF' },
  { label: 'Albania', value: 'AL' },
  { label: 'Algeria', value: 'DZ' },
  { label: 'Andorra', value: 'AD' },
  { label: 'Angola', value: 'AO' },
  { label: 'Antigua and Barbuda', value: 'AG' },
  { label: 'Argentina', value: 'AR' },
  { label: 'Armenia', value: 'AM' },
  { label: 'Australia', value: 'AU' },
  { label: 'Austria', value: 'AT' },
  { label: 'Azerbaijan', value: 'AZ' },
  { label: 'Bahamas', value: 'BS' },
  { label: 'Bahrain', value: 'BH' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Barbados', value: 'BB' },
  { label: 'Belarus', value: 'BY' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Belize', value: 'BZ' },
  { label: 'Benin', value: 'BJ' },
  { label: 'Bhutan', value: 'BT' },
  { label: 'Bolivia', value: 'BO' },
  { label: 'Bosnia and Herzegovina', value: 'BA' },
  { label: 'Botswana', value: 'BW' },
  { label: 'Brazil', value: 'BR' },
  { label: 'Brunei', value: 'BN' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Burkina Faso', value: 'BF' },
  { label: 'Burundi', value: 'BI' },
  { label: 'Cambodia', value: 'KH' },
  { label: 'Cameroon', value: 'CM' },
  { label: 'Canada', value: 'CA' },
  { label: 'Cape Verde', value: 'CV' },
  { label: 'Central African Republic', value: 'CF' },
  { label: 'Chad', value: 'TD' },
  { label: 'Chile', value: 'CL' },
  { label: 'China', value: 'CN' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Comoros', value: 'KM' },
  { label: 'Congo', value: 'CG' },
  { label: 'Costa Rica', value: 'CR' },
  { label: 'Croatia', value: 'HR' },
  { label: 'Cuba', value: 'CU' },
  { label: 'Cyprus', value: 'CY' },
  { label: 'Czech Republic', value: 'CZ' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Djibouti', value: 'DJ' },
  { label: 'Dominica', value: 'DM' },
  { label: 'Dominican Republic', value: 'DO' },
  { label: 'East Timor', value: 'TL' },
  { label: 'Ecuador', value: 'EC' },
  { label: 'Egypt', value: 'EG' },
  { label: 'El Salvador', value: 'SV' },
  { label: 'Equatorial Guinea', value: 'GQ' },
  { label: 'Eritrea', value: 'ER' },
  { label: 'Estonia', value: 'EE' },
  { label: 'Ethiopia', value: 'ET' },
  { label: 'Fiji', value: 'FJ' },
  { label: 'Finland', value: 'FI' },
  { label: 'France', value: 'FR' },
  { label: 'Gabon', value: 'GA' },
  { label: 'Gambia', value: 'GM' },
  { label: 'Georgia', value: 'GE' },
  { label: 'Germany', value: 'DE' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Greece', value: 'GR' },
  { label: 'Grenada', value: 'GD' },
  { label: 'Guatemala', value: 'GT' },
  { label: 'Guinea', value: 'GN' },
  { label: 'Guinea-Bissau', value: 'GW' },
  { label: 'Guyana', value: 'GY' },
  { label: 'Haiti', value: 'HT' },
  { label: 'Honduras', value: 'HN' },
  { label: 'Hungary', value: 'HU' },
  { label: 'Iceland', value: 'IS' },
  { label: 'India', value: 'IN' },
  { label: 'Indonesia', value: 'ID' },
  { label: 'Iran', value: 'IR' },
  { label: 'Iraq', value: 'IQ' },
  { label: 'Ireland', value: 'IE' },
  { label: 'Israel', value: 'IL' },
  { label: 'Italy', value: 'IT' },
  { label: 'Ivory Coast', value: 'CI' },
  { label: 'Jamaica', value: 'JM' },
  { label: 'Japan', value: 'JP' },
  { label: 'Jordan', value: 'JO' },
  { label: 'Kazakhstan', value: 'KZ' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Kiribati', value: 'KI' },
  { label: 'Kuwait', value: 'KW' },
  { label: 'Kyrgyzstan', value: 'KG' },
  { label: 'Laos', value: 'LA' },
  { label: 'Latvia', value: 'LV' },
  { label: 'Lebanon', value: 'LB' },
  { label: 'Lesotho', value: 'LS' },
  { label: 'Liberia', value: 'LR' },
  { label: 'Libya', value: 'LY' },
  { label: 'Liechtenstein', value: 'LI' },
  { label: 'Lithuania', value: 'LT' },
  { label: 'Luxembourg', value: 'LU' },
  { label: 'Madagascar', value: 'MG' },
  { label: 'Malawi', value: 'MW' },
  { label: 'Malaysia', value: 'MY' },
  { label: 'Maldives', value: 'MV' },
  { label: 'Mali', value: 'ML' },
  { label: 'Malta', value: 'MT' },
  { label: 'Marshall Islands', value: 'MH' },
  { label: 'Mauritania', value: 'MR' },
  { label: 'Mauritius', value: 'MU' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Micronesia', value: 'FM' },
  { label: 'Moldova', value: 'MD' },
  { label: 'Monaco', value: 'MC' },
  { label: 'Mongolia', value: 'MN' },
  { label: 'Montenegro', value: 'ME' },
  { label: 'Morocco', value: 'MA' },
  { label: 'Mozambique', value: 'MZ' },
  { label: 'Myanmar', value: 'MM' },
  { label: 'Namibia', value: 'NA' },
  { label: 'Nauru', value: 'NR' },
  { label: 'Nepal', value: 'NP' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'New Zealand', value: 'NZ' },
  { label: 'Nicaragua', value: 'NI' },
  { label: 'Niger', value: 'NE' },
  { label: 'Nigeria', value: 'NG' },
  { label: 'North Korea', value: 'KP' },
  { label: 'North Macedonia', value: 'MK' },
  { label: 'Norway', value: 'NO' },
  { label: 'Oman', value: 'OM' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Palau', value: 'PW' },
  { label: 'Palestine', value: 'PS' },
  { label: 'Panama', value: 'PA' },
  { label: 'Papua New Guinea', value: 'PG' },
  { label: 'Paraguay', value: 'PY' },
  { label: 'Peru', value: 'PE' },
  { label: 'Philippines', value: 'PH' },
  { label: 'Poland', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Qatar', value: 'QA' },
  { label: 'Romania', value: 'RO' },
  { label: 'Russia', value: 'RU' },
  { label: 'Rwanda', value: 'RW' },
  { label: 'Saint Kitts and Nevis', value: 'KN' },
  { label: 'Saint Lucia', value: 'LC' },
  { label: 'Saint Vincent and the Grenadines', value: 'VC' },
  { label: 'Samoa', value: 'WS' },
  { label: 'San Marino', value: 'SM' },
  { label: 'Sao Tome and Principe', value: 'ST' },
  { label: 'Saudi Arabia', value: 'SA' },
  { label: 'Senegal', value: 'SN' },
  { label: 'Serbia', value: 'RS' },
  { label: 'Seychelles', value: 'SC' },
  { label: 'Sierra Leone', value: 'SL' },
  { label: 'Singapore', value: 'SG' },
  { label: 'Slovakia', value: 'SK' },
  { label: 'Slovenia', value: 'SI' },
  { label: 'Solomon Islands', value: 'SB' },
  { label: 'Somalia', value: 'SO' },
  { label: 'South Africa', value: 'ZA' },
  { label: 'South Korea', value: 'KR' },
  { label: 'South Sudan', value: 'SS' },
  { label: 'Spain', value: 'ES' },
  { label: 'Sri Lanka', value: 'LK' },
  { label: 'Sudan', value: 'SD' },
  { label: 'Suriname', value: 'SR' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Switzerland', value: 'CH' },
  { label: 'Syria', value: 'SY' },
  { label: 'Taiwan', value: 'TW' },
  { label: 'Tajikistan', value: 'TJ' },
  { label: 'Tanzania', value: 'TZ' },
  { label: 'Thailand', value: 'TH' },
  { label: 'Togo', value: 'TG' },
  { label: 'Tonga', value: 'TO' },
  { label: 'Trinidad and Tobago', value: 'TT' },
  { label: 'Tunisia', value: 'TN' },
  { label: 'Turkey', value: 'TR' },
  { label: 'Turkmenistan', value: 'TM' },
  { label: 'Tuvalu', value: 'TV' },
  { label: 'Uganda', value: 'UG' },
  { label: 'Ukraine', value: 'UA' },
  { label: 'United Arab Emirates', value: 'AE' },
  { label: 'United Kingdom', value: 'GB' },
  { label: 'United States', value: 'US' },
  { label: 'Uruguay', value: 'UY' },
  { label: 'Uzbekistan', value: 'UZ' },
  { label: 'Vanuatu', value: 'VU' },
  { label: 'Vatican City', value: 'VA' },
  { label: 'Venezuela', value: 'VE' },
  { label: 'Vietnam', value: 'VN' },
  { label: 'Yemen', value: 'YE' },
  { label: 'Zambia', value: 'ZM' },
  { label: 'Zimbabwe', value: 'ZW' },
];
